// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("BetfairAPING.Console")]
[assembly: AssemblyDescriptionAttribute("Command-line interface for Betfair API-NG")]
[assembly: GuidAttribute("2a120bd3-a369-47ed-a67d-26823d332807")]
[assembly: AssemblyProductAttribute("BetfairAPING.Console")]
[assembly: AssemblyCopyrightAttribute("Copyright 2015 Russell Gray <russgray@gmail.com>")]
[assembly: AssemblyVersionAttribute("0.2.0.26")]
[assembly: AssemblyFileVersionAttribute("0.2.0.26")]
[assembly: AssemblyInformationalVersionAttribute("0.2.0-unstable.26+26.Branch.develop.Sha.3b9f807191997bcd57df4637e5bdf2822364c4ac")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.0.26";
    }
}
