// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("BetfairAPING.Console")]
[assembly: AssemblyDescriptionAttribute("Command-line interface for Betfair API-NG")]
[assembly: GuidAttribute("2a120bd3-a369-47ed-a67d-26823d332807")]
[assembly: AssemblyProductAttribute("BetfairAPING.Console")]
[assembly: AssemblyCopyrightAttribute("Copyright 2015 Russell Gray <russgray@gmail.com>")]
[assembly: AssemblyVersionAttribute("0.2.0.21")]
[assembly: AssemblyFileVersionAttribute("0.2.0.21")]
[assembly: AssemblyInformationalVersionAttribute("0.2.0-unstable.21+21.Branch.develop.Sha.4fadbda523fdb30adee57e5d865cb047d819cd5e")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.0.21";
    }
}
